# Generated by Django 3.0.6 on 2020-06-02 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20200601_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='rol3',
            field=models.CharField(choices=[('ADM', 'Admin'), ('PRO', 'Professional'), ('CST', 'Customer')], default='CST', max_length=10),
        ),
    ]
